import type * as DocsPlugin from '@docusaurus/plugin-content-docs';

export default {
    // default https://docusaurus.io/docs/sidebar/autogenerated sidebar slice based on hierarchy under docs/
    refarchSidebar: [{ type: 'autogenerated', dirName: 'ref-arch' }],
    northStarSidebar: [{ type: 'autogenerated', dirName: 'north-star-arch' }],
    goldenPathSidebar: [{ type: 'autogenerated', dirName: 'golden-path' }],
    globalStandardsForAgenticAISidebar: [{ type: 'autogenerated', dirName: 'agent' }],
    communitySidebar: [{ type: 'autogenerated', dirName: 'community' }],

} satisfies DocsPlugin.SidebarsConfig;
