import type { EditorThemeClasses } from 'lexical';
import styles from './index.module.css';

const theme: EditorThemeClasses = {
    ltr: styles.ltr,
    rtl: styles.rtl,
    placeholder: styles.editorPlaceholder,
    paragraph: styles.editorParagraph,
    quote: styles.editorQuote,
    heading: {
        h1: styles.editorH1,
        h2: styles.editorH2,
        h3: styles.editorH3,
        h4: styles.editorH4,
        h5: styles.editorH5,
    },
    list: {
        nested: {
            listitem: styles.editorNestedListItem,
        },
        ol: styles.editorOList,
        ul: styles.editorUList,
        listitem: styles.editorListItem,
    },
    link: styles.editorLink,
    text: {
        bold: styles.editorTextBold,
        italic: styles.editorTextItalic,
        underline: styles.editorTextUnderline,
        strikethrough: styles.editorTextStrikethrough,
        underlineStrikethrough: styles.editorTextUnderlineStrikethrough,
        code: styles.editorTextCode,
    },
    image: styles.editorImage,
    code: styles.editorCode,
    codeHighlight: {
        atrule: styles.editorTokenAttr,
        attr: styles.editorTokenAttr,
        boolean: styles.editorTokenProperty,
        builtin: styles.editorTokenSelector,
        cdata: styles.editorTokenComment,
        char: styles.editorTokenSelector,
        class: styles.editorTokenFunction,
        'class-name': styles.editorTokenFunction,
        comment: styles.editorTokenComment,
        constant: styles.editorTokenProperty,
        deleted: styles.editorTokenProperty,
        doctype: styles.editorTokenComment,
        entity: styles.editorTokenOperator,
        function: styles.editorTokenFunction,
        important: styles.editorTokenVariable,
        inserted: styles.editorTokenSelector,
        keyword: styles.editorTokenAttr,
        namespace: styles.editorTokenVariable,
        number: styles.editorTokenProperty,
        operator: styles.editorTokenOperator,
        prolog: styles.editorTokenComment,
        property: styles.editorTokenProperty,
        punct: styles.editorTokenPunctuation,
        regex: styles.editorTokenVariable,
        selector: styles.editorTokenSelector,
        string: styles.editorTokenSelector,
        symbol: styles.editorTokenProperty,
        tag: styles.editorTokenProperty,
        url: styles.editorTokenOperator,
        variable: styles.editorTokenVariable,
    },
};

export default theme;
