name: Deploy main site to GitHub Pages

on:
  # for local PR builds esp. builds in forked repositories
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    environment: github-pages
    env:
      VALIDATOR_API_URL: ${{ secrets.VALIDATOR_API_URL }}
      BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
      EXPRESS_BACKEND_URL: ${{ secrets.EXPRESS_BACKEND_URL }}
      VALIDATOR_RULES_API_URL: ${{ secrets.VALIDATOR_RULES_API_URL }}
      VALIDATOR_OAUTH_AUTH_URL: ${{ secrets.VALIDATOR_OAUTH_AUTH_URL }}
      VALIDATOR_OAUTH_CLIENT_ID: ${{ secrets.VALIDATOR_OAUTH_CLIENT_ID }}
      VALIDATOR_OAUTH_CLIENT_SECRET: ${{ secrets.VALIDATOR_OAUTH_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # fetch complete history for step "export drawios" to safely determine
          # date of last update to drawio files via git log
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Get pages deployment URL
        run: |
          pages_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          url=$(echo "$pages_url"|cut -d'/' -f 1)//$(echo "$pages_url"|cut -d'/' -f 3)
          base_url=$(echo "$pages_url"|cut -d'/' -f 4)
          echo "url=$url" >> "$GITHUB_ENV"
          echo "base_url=$base_url" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch docusaurus.config.ts
        run: |
          sed -E -i "s^url:(..*)^url: '$url',^g" docusaurus.config.ts
          sed -E -i "s^const baseUrl = '(.*)';^const baseUrl = '/$base_url';^g" docusaurus.config.ts

      - name: Fetch contributors details from GitHub API
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: node src/_scripts/_fetch-contributors-details.js

      - name: Cache drawio svgs
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.cache/architecture-center/drawio-svgs
          key: drawio-svgs-runner-${{ runner.os }}-branch-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            drawio-svgs-runner-${{ runner.os }}-branch-${{ github.ref_name }}-

      - name: Export drawios to svgs
        run: CACHE_ENABLED=1 DOCKER=1 node src/_scripts/_export-drawios/_export.js

      - name: Generate validation rules
        run: node src/_scripts/_generate-validator-rules.js

      - name: Build Website
        run: npm run build

      - name: Update drawio links with hashed URLs
        run: node src/_scripts/_update-drawio-links.js

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: build

  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: success()
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
